language: php

# Add php version so composer doesn't complain
php:
  - 7.1

services:
  - docker

env:
  - DRUPAL_ROOT=/var/www/html

before_script:
  - docker pull statonlab/tripal3
  - git clone https://github.com/statonlab/mail_cli.git

script:
  - docker run -it -d --rm --name tripal -v "$(pwd)":/modules/automated_annotation -v "$(pwd)/mail_cli":/modules/mail_cli statonlab/tripal3
  - sleep 30 # We pause here so postgres and apache complete booting up
  - docker exec -it tripal drush pm-enable -y automated_annotation
  - docker exec -it tripal bash -c "cd /modules/automated_annotation && composer install && DRUPAL_ROOT=/var/www/html ./vendor/bin/phpunit"
