<?php

require_once 'includes/Services/Dumper.php';
require_once 'includes/Services/FastaDumper.php';
require_once 'includes/Services/AnnotationFinder.php';
require_once 'includes/api/automated_annotation.api.inc';


/**
 * Implements hook_menu().
 */
function automated_annotation_menu() {
  $items = [];

  $items['admin/config/automated-annotation'] = [
    'title' => 'Automated Annotation',
    'description' => 'Configure the email addresses that receive annotation notifications.',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['automated_annotation_settings_form'],
    'access arguments' => ['administer tripal'],
    'file' => 'includes/automated_annotation_settings.form.inc',
  ];

  $items['admin/config/automated-annotation/settings'] = [
    'title' => 'Settings',
    'description' => 'Configure the email addresses that receive annotation notifications.',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  ];

  $items['admin/config/automated-annotation/report'] = [
    'title' => 'Annotations Report',
    'description' => 'Configure the email addresses that receive annotation notifications.',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['automated_annotation_report_form'],
    'access arguments' => ['administer tripal'],
    'file' => 'includes/automated_annotation_report.page.inc',
    'type' => MENU_LOCAL_TASK,
  ];

  return $items;
}

/**
 * Find features that need annotation.
 *
 * @throws \MailCLIException
 */
function automated_annotation_find_features_with_no_annotations() {

}
